name: tv_shows
description: A simple app that helps you keep track of shows and episodes you watched.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_secure_storage: 4.2.1
  json_annotation: ^4.0.1
  image_picker: ^0.8.3+2
  loggy: ^2.0.0+1
  flutter_loggy_dio: ^2.0.0+3
  provider: ^5.0.0
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.1
  json_serializable: ^4.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Karla
      fonts:
        - asset: assets/fonts/Karla-Regular.ttf
        - asset: assets/fonts/Karla-Bold.ttf
          weight: 700
    - family: TVShowsIcons
      fonts:
        - asset: assets/fonts/icons/TVShowsIcons.ttf